version: '3'
services:
  http:
    build: .
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./letsencrypt:/etc/letsencrypt
      - ./letsencrypt-log:/var/log/letsencrypt
    # ports:
    #   - "80:80"
    #   - "443:443"